### PR TITLE
add man page

### PR DESCRIPTION
**Pull request by JR1994**
I wrote the following man page for mbpfan and would like to submit it.

[mbpfan.1.gz](https://github.com/rvega/Fan-Control-Daemon/files/344233/mbpfan.1.gz)

### CODE REVIEW

**Comment by rvega** [comment]
Wow! impressive. I'll take a close look soon and merge :)

**Comment by JR1994** [comment]
On 07/01, Rafael Vega wrote:

> Wow! impressive. I'll take a close look soon and merge :) 
> 
> Thanks! has anyone considered submitting a package to Debian? I would be intrested. I already built the .deb file. 

-Herminio

**Comment by rvega** [comment]
Do you guys want to take ownership of this repo? You are making way more work than me and I'll be moving away from Apple hardware soon.

**Comment by rvega** [comment]
I wrote a new readme handing ownership of this project to @dgraziotin. Thanks for submitting the pull requests here but I'm not into Apple hardware anymore and you guys are doing much more than me so, cheers and good luck! :)

**Comment by dgraziotin** [comment]
Hi! I am somehow confused by this chain of commits here. Seems that @JR1994 wanted to push something to @rvega repo but contained my fork?

By the way @rvega, my mbpfan was started as an educational project for refreshing C. I used your Fan-Control-Daemon as a starting skeleton. Then it somehow gained attention from some distros users (e.g., Arch Linux). I am acknowledging you in the README file and on the website :-)

**Comment by JR1994** [comment]
I am sorry I did a pull request on both pages when I should have only done
yours since I basing my commits off your tree.

**Comment by dgraziotin** [comment]
@JR1994 no problem at all, and thank you for your contribution!

**Comment by rvega** [comment]
@dgraziotin Thanks for mentioning me :)

**Pull request closed without merging**
